"""Adding bill field to subscription

Revision ID: 4dc1c9d4847b
Revises: 6dda384f817b
Create Date: 2022-07-02 17:11:33.015909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc1c9d4847b'
down_revision = '6dda384f817b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bills_subscription_id', table_name='bills')
    op.drop_constraint('bills_subscription_id_fkey', 'bills', type_='foreignkey')
    op.drop_column('bills', 'subscription_id')
    op.add_column('subscriptions', sa.Column('bill_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_subscriptions_bill_id'), 'subscriptions', ['bill_id'], unique=False)
    op.create_foreign_key(None, 'subscriptions', 'bills', ['bill_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_subscriptions_bill_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'bill_id')
    op.add_column('bills', sa.Column('subscription_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key('bills_subscription_id_fkey', 'bills', 'subscriptions', ['subscription_id'], ['id'])
    op.create_index('ix_bills_subscription_id', 'bills', ['subscription_id'], unique=False)
    # ### end Alembic commands ###
