"""Adding status on bills and suibscriptions

Revision ID: 76c445bbdf3d
Revises: 96d5a1b9cb78
Create Date: 2022-06-29 16:44:25.514436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c445bbdf3d'
down_revision = '96d5a1b9cb78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('status', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'status')
    op.drop_column('bills', 'status')
    # ### end Alembic commands ###
