"""Init tables

Revision ID: 96d5a1b9cb78
Revises: 
Create Date: 2022-06-29 11:19:01.774464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d5a1b9cb78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('_created', sa.DateTime(), nullable=True),
    sa.Column('_updated', sa.DateTime(), nullable=True),
    sa.Column('_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices__created'), 'prices', ['_created'], unique=False)
    op.create_index(op.f('ix_prices_value'), 'prices', ['value'], unique=True)
    op.create_table('plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('_created', sa.DateTime(), nullable=True),
    sa.Column('_updated', sa.DateTime(), nullable=True),
    sa.Column('_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('price_id', sa.String(length=36), nullable=True),
    sa.Column('plan_name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans__created'), 'plans', ['_created'], unique=False)
    op.create_index(op.f('ix_plans_plan_name'), 'plans', ['plan_name'], unique=True)
    op.create_index(op.f('ix_plans_price_id'), 'plans', ['price_id'], unique=False)
    op.create_table('promotions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('_created', sa.DateTime(), nullable=True),
    sa.Column('_updated', sa.DateTime(), nullable=True),
    sa.Column('_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('from_quantity', sa.Integer(), nullable=True),
    sa.Column('to_quantity', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('promotion_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions__created'), 'promotions', ['_created'], unique=False)
    op.create_index(op.f('ix_promotions_plan_id'), 'promotions', ['plan_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('_created', sa.DateTime(), nullable=True),
    sa.Column('_updated', sa.DateTime(), nullable=True),
    sa.Column('_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('price_id', sa.String(length=36), nullable=True),
    sa.Column('promotion_id', sa.String(length=36), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions__created'), 'subscriptions', ['_created'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_price_id'), 'subscriptions', ['price_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_promotion_id'), 'subscriptions', ['promotion_id'], unique=False)
    op.create_table('bills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('_created', sa.DateTime(), nullable=True),
    sa.Column('_updated', sa.DateTime(), nullable=True),
    sa.Column('_deleted', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('subscription_id', sa.String(length=36), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=15, scale=3, asdecimal=False), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('sub_total', sa.DECIMAL(precision=15, scale=3, asdecimal=False), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills__created'), 'bills', ['_created'], unique=False)
    op.create_index(op.f('ix_bills_subscription_id'), 'bills', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bills_subscription_id'), table_name='bills')
    op.drop_index(op.f('ix_bills__created'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_subscriptions_promotion_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_price_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions__created'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_promotions_plan_id'), table_name='promotions')
    op.drop_index(op.f('ix_promotions__created'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_plans_price_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_plan_name'), table_name='plans')
    op.drop_index(op.f('ix_plans__created'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_prices_value'), table_name='prices')
    op.drop_index(op.f('ix_prices__created'), table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###
