"""Adding bill backref field to subscription on bill-2

Revision ID: 9abf7cde7140
Revises: 9e6b6dc2b8cc
Create Date: 2022-07-02 17:25:35.212210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9abf7cde7140'
down_revision = '9e6b6dc2b8cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('subscription_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_bills_subscription_id'), 'bills', ['subscription_id'], unique=False)
    op.create_foreign_key(None, 'bills', 'subscriptions', ['subscription_id'], ['id'])
    op.drop_index('ix_subscriptions_bill_id', table_name='subscriptions')
    op.drop_constraint('subscriptions_bill_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'bill_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('bill_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key('subscriptions_bill_id_fkey', 'subscriptions', 'bills', ['bill_id'], ['id'])
    op.create_index('ix_subscriptions_bill_id', 'subscriptions', ['bill_id'], unique=False)
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_index(op.f('ix_bills_subscription_id'), table_name='bills')
    op.drop_column('bills', 'subscription_id')
    # ### end Alembic commands ###
