"""Adding bill backref field to subscription on bill

Revision ID: 9e6b6dc2b8cc
Revises: 4dc1c9d4847b
Create Date: 2022-07-02 17:21:41.402956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6b6dc2b8cc'
down_revision = '4dc1c9d4847b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
