# ROUTES
URI_ATTR: str = 'uri'
VIEW_ATTR: str = 'view'
METHOD_ATTR: str = 'methods'
MIDDLEWARES_ATTR: str = 'middlewares'

# Route attrs <key>:<default>
ROUTE_ATTRIBUTES = {
    URI_ATTR: None,
    VIEW_ATTR: None,
    MIDDLEWARES_ATTR: [],
    METHOD_ATTR: None
}

# Must be present to enable API route
REQUIRED_ATTRIBUTES = [
    URI_ATTR, VIEW_ATTR
]

# Method
GET = 'GET'
POST = 'POST'
PATCH = 'PATCH'
DELETE = 'DELETE'
PUT = 'PUT'

ALLOWED_METHODS = {GET, PUT, POST, PATCH, DELETE}

SUCCESS_RESPONSE_CODE = 200
CREATED_RESPONSE_CODE = 201
NO_CONTENT_RESPONSE_CODE = 204

BAD_REQUEST_RESPONSE_CODE = 400
UNAUTHORIZED_RESPONSE_CODE = 401
FORBIDDEN_RESPONSE_CODE = 403
NOT_FOUND_RESPONSE_CODE = 404
NOT_ALLOW_RESPONSE_CODE = 405
UNPROCESSABLE_ENTITY_RESPONSE_CODE = 422
CONFLICT_RESPONSE_CODE = 409

INTERNAL_ERROR_RESPONSE_CODE = 500
SERVICE_UNAVAILABLE_RESPONSE_CODE = 503

ISO_8601 = '%Y-%m-%dT%H:%M:%S.%fZ'

# Default limit for API
DEFAULT_LIMIT = 25

ACCOUNT_SERVICE_URL = ""
